/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#include "snippet_dot_c_test.h"

#include "gtest/gtest.h"

namespace UTBot {
// Some tests for function 'main' were skipped, as execution of function is out of timeout.

// Tests for main were not generated. Maybe the function is too complex.



#pragma region regression
TEST(regression, calculateControl_test_1)
{
    float actual = calculateControl(0.000000e+00, 0.000000e+00, 0.000000e+00);
    EXPECT_FLOAT_EQ(0.000000e+00, actual);
}

#pragma endregion
}