/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#include "snippet_dot_c_test.h"

#include "gtest/gtest.h"

namespace UTBot {


#pragma region regression
TEST(regression, calculateControl_test_1)
{
    float actual = calculateControl(0.000000e+00, 0.000000e+00, 0.000000e+00);
    EXPECT_FLOAT_EQ(0.000000e+00, actual);
}

TEST(regression, main_test_1)
{
    int actual = main();
    EXPECT_EQ(0, actual);
}

#pragma endregion
}